Post/urls.py
from django.urls import path
from . import views


app_name = 'post'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('about_me', views.about_me, name='about_me'),
    path('post_list', views.post_list, name='post_list'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:slug>/',views.post_detail,name='post_detail'),
]

SisOp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pregunta.urls', namespace='pregunta'))
]

Diamat/templates/about_me.html
{% extends 'base.html' %}

{%block title%} About Me{% endblock %}

{% block content %}
    <div class="container">
        <div class="my-3 card shadow">
            <div class="card-header">
                <h1>About Me</h1>
            </div>
            <div class="card-text p-3">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                    Etiam accumsan pulvinar tincidunt. 
                    Phasellus congue eros vel finibus molestie. 
                    Etiam eu magna pulvinar, ullamcorper neque ornare, euismod erat.
                     Fusce vitae augue id purus finibus venenatis. Sed vel velit pretium, imperdiet nisl ac, mollis ex. Nulla eu ante id nisl auctor lobortis non non justo. Suspendisse potenti. Mauris semper enim ut dolor eleifend, eu viverra nisi efficitur. Sed tristique cursus blandit. Integer vitae urna maximus, faucibus sapien sit amet, laoreet erat. Pellentesque dictum a turpis in imperdiet.
                </p><p>
                    Sed consequat risus eu magna pulvinar imperdiet. In rutrum elit vel mauris volutpat bibendum. Mauris eget velit non est laoreet aliquam vitae vel odio. Mauris mollis posuere felis sed sagittis. Aenean dapibus sapien ac ornare finibus. Donec gravida leo non felis scelerisque, sit amet ultrices neque feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam sed feugiat eros. Nulla finibus, turpis id elementum fermentum, turpis odio porta ligula, sed posuere massa augue at sem. Quisque in diam convallis, vestibulum urna vel, iaculis tortor.
                </p><p>
                    Suspendisse hendrerit tempus condimentum. Mauris in nunc in lacus maximus viverra at at nulla. Donec non bibendum sapien, in bibendum mi. Praesent gravida congue turpis, in varius sem convallis non. Sed vel tristique ligula. Fusce viverra blandit sapien in fermentum. Phasellus consectetur, lectus sit amet cursus posuere, mauris mi malesuada ante, vitae congue turpis tellus quis urna. Nulla diam leo, fringilla ut condimentum ut, tincidunt quis sapien. Nam ut leo eget lorem dictum molestie sit amet id eros. Curabitur at nibh congue, tristique elit at, egestas libero. Proin vitae imperdiet velit. Duis pellentesque cursus suscipit. In sit amet vestibulum quam.
                </p><p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a velit id metus accumsan dictum. Donec fermentum pulvinar congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consequat neque in convallis eleifend. Praesent auctor molestie elit, sed imperdiet sapien porttitor eu. Phasellus ut fermentum libero. Suspendisse at nisl nulla. Integer sollicitudin augue ut velit ultricies hendrerit. Nulla facilisi. Donec ullamcorper neque a dignissim viverra. In pharetra lacus ac turpis dapibus, sit amet sollicitudin purus ullamcorper. Aenean tempus turpis nec rutrum porttitor.
                </p><p>
                    Nullam mattis sit amet libero eu elementum. Donec est tellus, venenatis pretium felis eu, fringilla lobortis nunc. Nam et augue nec massa convallis pharetra vel ut velit. Fusce eget felis mollis, pharetra lorem a, varius magna. Suspendisse potenti. Ut rutrum hendrerit enim, vel dictum odio dignissim placerat. Aenean quis molestie justo. Suspendisse dapibus urna eu orci tincidunt vestibulum. Vivamus id metus efficitur, sollicitudin nibh in, hendrerit orci. Integer in erat non enim pretium lacinia in at odio. Morbi a magna in ligula porttitor tristique.
                </p><p>
                    Pellentesque id lorem hendrerit, vestibulum risus sed, placerat leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Vestibulum eu interdum felis. Cras venenatis pulvinar mollis. Ut vehicula venenatis nisi, sed auctor libero vulputate eget. Suspendisse vel rutrum arcu, eu feugiat diam. Cras tempor sagittis hendrerit.</p>
                </p>
            </div>
        </div>
        
    </div>

{% endblock %}

Diamat/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>

    <!--Meta-->
    <meta charset="UTF-8">

    <meta name="description" content="Personal blog.">
    <meta name="author" content="Erik B. Terres">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Web CSS-->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">

    <!-- Basic libraries -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/\bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81i\uXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>

<body>
    {% if anchor %}
        <script type='text/javascript'>
        $(document).ready(function(){
            window.location = '#{{ anchor }}'
        });
        </script>
    {% endif %}
    
<div class="content">
    <!-- Navbar  -->
    <div class="navbar navbar-expand-lg navbar-light  bg-danger shadow">
        <a href="/" class="web-title navbar-brand text-white font-weight-bold" style ="font-size: 2rem;">Diamat</a>
        <a href="{% url 'post:about_me' %}" >About Me</a>
    </div>

    <!-- Main Body -->
    <div id="main-content">
        <div class="justify-content-center mx-5" >
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
    <footer class="footer py-4 bg-dark text-white-50">
        <div class="container text-center">
            <small>Copyright &copy; Your Website</small>
        </div>
    </footer>

</body>
</html>

Diamat/templates/home.html
{% extends 'base.html'%}

{% block title%} Diamat | Home {% endblock %}
{% block content %}

<!-- Noticias destacadas -->
<div class="my-3">
    <h1 class="header text-center">Post Destacados</h1>
    <div class="shadow">
        {% include "post/popular_post.html" with posts=best_posts %}
    </div>
   
</div>

<!-- Menu de abajo -->
<div class ="container" >
    <div class="col ">
        <h1> Entradas más recientes</h1>
        {% include "post/list.html" with posts=posts %}
        {% include "pagination.html" with page=posts %}
    </div>
</div>
{% endblock %}

Diamat/templates/incorrect.html
<html>
    Incorrect
</html>

Diamat/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
            <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
            </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>